### ISSUE TITLE
'প','ল' Joining issue in ANSI

### ISSUE THREAD

**Issue by DhimanSarkar** [mugli/Avro-Keyboard#8]
In some software, like CorelDraw, Photoshop, there's an issue while joining 'প','ল' to product 'প্ল' in ANSI.
AvroKeyboard implements this as '**c-**' but this doesn't produce the join rather '**c−**' this produces the join. So **U+2212 (MINUS SIGN −) should be used.**
![Annotation 2020-05-05 212419](https://user-images.githubusercontent.com/24076024/81087813-c6c46180-8f17-11ea-888f-288728c486c7.jpg)

**Comment by israilkhan-bit** [comment]
আপনাদের অভ্র কিবোর্ড এ.এন.এস.আই এ একটা বাগ আছে

বুল্লা এর আউটপুট আসার কথা eyj−v ( কেননা কালপুরুষ এ.এন.এস.আই ফন্টে কিন্তু u+2212 বা " − " ব্যাবহার করেছেন )
এখানে খেয়াল করুন "−" এবং"-" দুইটি কিন্তু এক নয় । দুইটির কোড ও আলাদা "−" = u+2212  এবং "-" =u +2d

কিন্তু আপনাদের সফটওয়্যার output  দেয় eyj-v (এখানে আপনারা মাইনাস সিম্বল ও হাইফেন এক করে ফেলেছেন । আউটপুট দেওয়া উচিত ছিল u+2212 অর্থাৎ মাইনাস সাইন  ব্যাবহার না করে হাইফেন ব্যবহার করেছেন


ওয়ার্ডে ল্ল লেখা গেলেও অন্যান্য
অনেক সফটওয়্যার এ বাংলা এ.এন.এস.আই দিয়ে  "ল্ল"  লিখা যায় না ।
